# **Welcome to numpy**

In [1]:
# Import the required libraries
import numpy as np
import time

In [ ]:
# Example of how much numpy is faster than list

def using_list():
    stp = time.time()
    x = range(10000)
    y = range(10000)
    result = [x[i] + y[i] for i in range(len(x))]
    edp = time.time()
    return edp - stp

def using_numpy():
    stn = time.time()
    a = np.arange(10000)
    b = np.arange(10000)
    result = a + b          # broadcasting
    edn = time.time()
    return edn - stn

In [ ]:
#driver's code

list_time = using_list()
numpy_time = using_numpy()

print(f"Time taken for python list :- {list_time:.4f} seconds")
print(f"Time taken for numpy array :- {numpy_time:.4f} seconds")

# note :- ".nf" is number of digits after decimal. here is '.4f'

Time taken for python list :- 0.0033 seconds
Time taken for numpy arry :- 0.0000 seconds


In [ ]:
# Initialize with integer values themselves
np.array((1, 2, 3))         #((elements))

array([1, 2, 3])

In [ ]:
# Initialize with all zero values (by default :- float format)
np.zeros((3, 4))            #((rows, columns))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Initialize with number you want (given format)
np.full((3, 4), 5)          #((rows, columns), element)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
# Initialize with random values
np.random.random((2, 3))        #((rows, columns))

array([[0.68723636, 0.73649898, 0.58753592],
       [0.60958885, 0.1536155 , 0.58285142]])

In [ ]:
# Convert 2d array to 1d array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Convert 1d array to 2d array
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(2, 3)       # reshape(rows_to_split, columns_to_split)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Convert 1d array to 3d array
arr = np.arange(24)

arr2 = arr.reshape(2, 4, 3)
arr2

# note :- here '2' is number of sub arrays in array
#              '4' is number of rows in particular sub arrays
#              '3' is number of columns in particular sub arrays

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
# Resize the array using '.shape' method
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9], 
                [10, 11, 12]])

print(f"Size before :- {arr.shape}")
arr.shape = (3, 4)          # arr.resize(3, 4) will works the same. 
print(f"Size after :- {arr.shape}")              

Size before :- (4, 3)
Size after :- (3, 4)


In [ ]:
# Create np array and sort
arr = np.array([2, 4, 7, 3, 1, 9, 8])

print(f"Before sorting :- {arr}")
print()
print(f"After sorting :- {np.sort(arr)}")

Before sorting :- [2 4 7 3 1 9 8]

After sorting :- [1 2 3 4 7 8 9]


In [ ]:
# Identify total number of an elements in an array
arr = np.array([[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]])

print(f"size of an array :- {arr.size}")

size of an array :- 9


In [ ]:
# Identify shape (rows * columns) of an array
arr = np.array([[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]])

print(f"shape of an array :- {arr.shape}")

shape of an array :- (3, 3)


In [ ]:
# Identify dimension of an array
arr = np.array([[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]])

print(f"dimension of an array :- {arr.ndim}")

dimension of an array :- 2


In [ ]:
# Identify data type of an array
arr = np.arange(24, dtype = float)

print(f"Data type is {arr.dtype}")

arr2 = arr.reshape(3, 4, 2)
arr2

Data type is float64


array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]])

In [ ]:
# Sum

# create a sample array
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

total = np.sum(arr)
print(f"Sum of elements in array :- {total}")

Sum of elements in array :- 45


In [ ]:
# Sum with an axis, while axis = 0
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

column_sum = np.sum(matrix, axis=0)     # return column wise sum
print(column_sum)

[12 15 18]


In [ ]:
# Sum with an axis, while axis = 1
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

row_sum = np.sum(matrix, axis=1)     # return row wise sum
print(row_sum)

[ 6 15 24]


In [ ]:
# Partial sum
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
partial_sum = np.sum(matrix [:2, :2])    # return the sum of elements comes in range
print(partial_sum)                       # of (0-2 rows, 0-2columns)

12


In [ ]:
# Subtraction

# create a sample array
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

result = np.subtract(arr1, arr2)
print(f"arr1-arr2 => {result}")

result = np.subtract(arr2, arr1)
print(f"arr2-arr1 => {result}")

arr1-arr2 => [-2 -2 -2 -2]
arr2-arr1 => [2 2 2 2]


In [ ]:
# Subtraction with scalar
arr = np.array([2, 3, 4, 5])
scalar = 2

result = np.subtract(arr, scalar)
result      # scalar value is subtracted from each element of an array

array([0, 1, 2, 3])

In [ ]:
# Concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 6])

np.concatenate((arr1, arr2))

array([1, 2, 3, 5, 6])

In [ ]:
# Multiply
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.multiply(a, b)

array([ 4, 10, 18])

In [ ]:
# Divide
arr1 = np.array([5, 12, 22])
arr2 = np.array([1, 4, 11])

np.divide(arr1, arr2)       # default :- float division

array([5., 3., 2.])

In [ ]:
# Exponentions
arr = np.array([2, 4, 5])
np.exp(arr)         # e^a  where eis euler's number(2.718)

array([  7.3890561 ,  54.59815003, 148.4131591 ])

In [ ]:
# SQRT
arr = np.array([4, 8, 25, 37])
np.sqrt(arr)

# Note :- There are so many built in methods in Numpy, these are just some of them.

array([2.        , 2.82842712, 5.        , 6.08276253])

In [ ]:
# Comparision (np.equal)

# 1 
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.equal(a, b)      # np.equal used for element wise comparision

array([False, False, False])

In [69]:
# 2
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

np.equal(a, b)      # np.equal used for element wise comparision

array([ True,  True,  True])

In [ ]:
# Comparision (np.array_equal)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.array_equal(a, b)    # np.array_equal used for array wise comparision

False

In [ ]:
# Aggregate functions
coffee_ban = np.array([20, 25, 30])
coffee_pune = np.array([15, 17, 20])
coffee_delhi = np.array([11, 12, 13])

print(f"minimum value :- {np.min(coffee_ban)}\n")
print(f"mean value :- {np.mean(coffee_ban)}\n")
print(f"median value :- {np.median(coffee_ban)}\n")
print(f"standard deviation :- {np.std(coffee_ban)}")

# Note :- There are so many aggregate function like these, you can check on internet
# and use based on you need.These are just some of them

minimum value :- 20

mean value :- 25.0

median value :- 25.0

standard deviation :- 4.08248290463863


In [ ]:
# Broadcasting *****
a = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])

b = np.array([5, 6])

result = a + b
result

# Note :- Dimension should be matched, otherwise it will throw "value error"

array([[ 6,  8],
       [ 8, 10],
       [10, 12]])

In [ ]:
# Slicing
matrix = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

submatrix = matrix[0:2, 0:2]
submatrix

# Note :- creating sub-arrays from original array known as slicing

array([[1, 2],
       [5, 6]])

In [ ]:
# Indexing
matrix = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]])

matrix[0:2, 0:2]

# Note :- Accessing array elements referring to its index number known as indexing

array([[1, 2],
       [5, 6]])

In [ ]:
# Delete
arr = np.array([1, 2, 3, 4, 5])
np.delete(arr, 2)                   # (array, index_of_element)

array([1, 2, 4, 5])

In [ ]:
# Masking
arr = np.array([1, 2, 3, 4, 5])

mask = arr <= 3
new_arr = arr[mask]
new_arr

array([1, 2, 3])

In [ ]:
# vstack (vertical stacking)
arr1 = np.array([[1, 2], 
                 [3, 4]])

arr2 = np.array([5, 6])

result = np.vstack((arr1, arr2))
result

# In vertical stacking, column wise dimension should be matched.

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# hstack (horizontal stacking)
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

result = np.hstack((arr1, arr2))
result

# In horizontal stacking, row wise dimension should be matched.

array([1, 2, 3, 4])

In [6]:
a = np.array([[1, 2], 
              [3, 4]])

b = np.array([[5, 6], 
              [7, 8]])

np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# column_stack
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

np.column_stack((arr1, arr2))           # also can be done using
                                        # np.transpose((arr1, arr2))
# Dimension before :- 2 * 4
# Dimension after :- 4 * 2

# Note :- simply for understanding you can say
        # rows becomes columns  &
        # columns becomes rows

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
# Spliting (np.split)

# syntax :- (array_name, no_of_splits)

arr = np.arange(10)
np.split(arr, 2)

# Note :- it is used when there are equal number of division.

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
# Spliting (np.array_split)

# syntax :- (array_name, no_of_splits)

arr = np.arange(10)
np.array_split(arr, 3)

# Note :- it is used when there are equal number of division as well as when
#         there are unequal number of divisions.

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
# np.hsplit (split column wise)

# 1 
arr = np.arange(1, 17).reshape(4, 4)       # 4 rows * 4 columns.
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
result = np.hsplit(arr, 2)              # or np.hsplit(arr, [1, 2]
result                                  # here, 1 & 2 are indexes of columns

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [43]:
# 2
arr = np.arange(1, 17).reshape(4, 4)        #           0   1   2   3
                                            #   
print(np.hsplit(arr, [2, 3]))               #   0       1   2   3   4
                                            #   1       5   6   7   8
                                            #   2       9   10  11  12
                                            #   3       13  14  15  16

# note :- Here [2, 3] are column indexes, that separate column having indexes 
#         2 and 3 seperate. Understand through diagram mentioned above.

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]]), array([[ 4],
       [ 8],
       [12],
       [16]])]


In [ ]:
# np.vsplit (split row wise)
arr = np.arange(16).reshape(4, 4)       # 4 rows * 4 columns.
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
result = np.vsplit(arr, 2)              # or np.vsplit(arr, [1, 2]
result                                  # here, 1 & 2 are indexes of rows

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

END

---